import Foundation

enum AppGroupConstants {
    static let suiteName = Bundle.main.object(forInfoDictionaryKey: "AppGroupID") as? String ?? "group.default.abstrakt"
    static let sharedClockTimeKey = "shared.clock.time"
    static let sharedClockDateKey = "shared.clock.date"
    static let sharedCalendarHeadlineKey = "shared.calendar.headline"
    static let sharedCalendarDetailKey = "shared.calendar.detail"
    static let sharedBatteryLevelKey = "shared.battery.level"
    static let sharedBatteryEstimatedHoursKey = "shared.battery.estimatedHours"
    static let sharedBatteryEstimatedMinutesKey = "shared.battery.estimatedMinutes"
    static let sharedBatteryIsChargingKey = "shared.battery.isCharging"
    static let sharedHealthStepsKey = "shared.health.steps"
    static let sharedHealthDistanceKilometersKey = "shared.health.distanceKilometers"
    static let sharedWeatherTemperatureKey = "shared.weather.temperature"
    static let sharedWeatherHighKey = "shared.weather.high"
    static let sharedWeatherLowKey = "shared.weather.low"
    static let sharedWeatherSymbolKey = "shared.weather.symbol"
    static let sharedPortalWeatherTemperatureKey = "shared.portal.weather.temperature"
    static let sharedPortalWeatherPlaceNameKey = "shared.portal.weather.placeName"
    static let sharedWidgetPresetsKey = "shared.widget.presets"
    static let sharedClassicWeatherKey = "shared.classic.weather"
    static let sharedSunEventWeatherKey = "shared.sunevent.weather"
    static let settingsAppFontThemeKey = "appFontTheme"
    static let settingsTemperatureUnitKey = "settings.temperatureUnit"
    static let settingsTemperatureDisplayKey = "settings.temperatureDisplay"
    static let settingsDistanceUnitKey = "settings.distanceUnit"
}
