import Foundation

enum AppGroupConstants {
    static let suiteName = "group.dapraws.abstrakt"
    static let sharedClockTimeKey = "shared.clock.time"
    static let sharedClockDateKey = "shared.clock.date"
    static let sharedCalendarHeadlineKey = "shared.calendar.headline"
    static let sharedCalendarDetailKey = "shared.calendar.detail"
    static let sharedBatteryLevelKey = "shared.battery.level"
    static let sharedBatteryEstimatedHoursKey = "shared.battery.estimatedHours"
    static let sharedBatteryEstimatedMinutesKey = "shared.battery.estimatedMinutes"
    static let sharedBatteryIsChargingKey = "shared.battery.isCharging"
    static let sharedHealthStepsKey = "shared.health.steps"
    static let sharedHealthDistanceKilometersKey = "shared.health.distanceKilometers"
    static let sharedWeatherTemperatureKey = "shared.weather.temperature"
    static let sharedWeatherHighKey = "shared.weather.high"
    static let sharedWeatherLowKey = "shared.weather.low"
    static let sharedWeatherSymbolKey = "shared.weather.symbol"
    static let sharedPortalWeatherTemperatureKey = "shared.portal.weather.temperature"
    static let sharedPortalWeatherPlaceNameKey = "shared.portal.weather.placeName"
    static let portalSelectedAppsKey = "portal.selectedApps"
    static let portalIconClipStyleKey = "portal.iconClipStyle"
    static let sharedWidgetPresetsKey = "shared.widget.presets"
    static let settingsAppFontThemeKey = "appFontTheme"
    static let settingsTemperatureUnitKey = "settings.temperatureUnit"
    static let settingsTemperatureDisplayKey = "settings.temperatureDisplay"
    static let settingsDistanceUnitKey = "settings.distanceUnit"
    static let sharedStorageTotalBytesKey = "shared.storage.totalBytes"
    static let sharedStorageAvailableBytesKey = "shared.storage.availableBytes"
}
